name: Run C++ Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Discord bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          ./bot
